package com.Alleoni.carRental.views;

import com.Alleoni.carRental.services.CarsService;
import org.springframework.beans.factory.annotation.Autowired;

/**
 *
 * @author guilh
 */
public class CarRegisterView extends javax.swing.JPanel {
    
    @Autowired
    private CarsService service;
    
    public CarRegisterView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHome = new javax.swing.JPanel();
        lblCustomerRegister = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblBirthDate = new javax.swing.JLabel();
        lblLicense = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtBirthDate = new javax.swing.JTextField();
        txtLicense = new javax.swing.JTextField();
        BtnRegister = new javax.swing.JButton();
        CategoryPanel = new javax.swing.JPanel();
        listCategories = new javax.swing.JComboBox<>();
        lblCategories = new javax.swing.JLabel();
        CategoryPanel2 = new javax.swing.JPanel();
        listCategories2 = new javax.swing.JComboBox<>();
        lblColor = new javax.swing.JLabel();
        CategoryPanel1 = new javax.swing.JPanel();
        listCategories1 = new javax.swing.JComboBox<>();
        lblBrands = new javax.swing.JLabel();

        panelHome.setToolTipText("");
        panelHome.setPreferredSize(new java.awt.Dimension(700, 400));

        lblCustomerRegister.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCustomerRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCustomerRegister.setText("Car Register");
        lblCustomerRegister.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblName.setText("Car Name");

        lblBirthDate.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblBirthDate.setText("Daily Rate");

        lblLicense.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblLicense.setText("License Plate");

        txtLicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLicenseActionPerformed(evt);
            }
        });

        BtnRegister.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnRegister.setText("Register");
        BtnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegisterActionPerformed(evt);
            }
        });

        listCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listCategoriesActionPerformed(evt);
            }
        });

        lblCategories.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCategories.setText("Categories");

        listCategories2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prata", "Branco", "Cinza", "Preto", "Vermelho", "Azul", "Marrom", "Verde", "Amarelo", " " }));
        listCategories2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listCategories2ActionPerformed(evt);
            }
        });

        lblColor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblColor.setText("Color");

        javax.swing.GroupLayout CategoryPanel2Layout = new javax.swing.GroupLayout(CategoryPanel2);
        CategoryPanel2.setLayout(CategoryPanel2Layout);
        CategoryPanel2Layout.setHorizontalGroup(
            CategoryPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CategoryPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CategoryPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblColor)
                    .addComponent(listCategories2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        CategoryPanel2Layout.setVerticalGroup(
            CategoryPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CategoryPanel2Layout.createSequentialGroup()
                .addComponent(lblColor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listCategories2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CategoryPanelLayout = new javax.swing.GroupLayout(CategoryPanel);
        CategoryPanel.setLayout(CategoryPanelLayout);
        CategoryPanelLayout.setHorizontalGroup(
            CategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CategoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCategories)
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(CategoryPanelLayout.createSequentialGroup()
                .addGroup(CategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CategoryPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listCategories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CategoryPanelLayout.setVerticalGroup(
            CategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CategoryPanelLayout.createSequentialGroup()
                .addComponent(lblCategories)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listCategories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CategoryPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listCategories1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listCategories1ActionPerformed(evt);
            }
        });

        lblBrands.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblBrands.setText("Brands");

        javax.swing.GroupLayout CategoryPanel1Layout = new javax.swing.GroupLayout(CategoryPanel1);
        CategoryPanel1.setLayout(CategoryPanel1Layout);
        CategoryPanel1Layout.setHorizontalGroup(
            CategoryPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CategoryPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CategoryPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBrands)
                    .addComponent(listCategories1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CategoryPanel1Layout.setVerticalGroup(
            CategoryPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CategoryPanel1Layout.createSequentialGroup()
                .addComponent(lblBrands)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listCategories1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnRegister)
                .addContainerGap())
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CategoryPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBirthDate)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName))))
                .addGap(15, 76, Short.MAX_VALUE)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CategoryPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLicense)
                    .addComponent(txtLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(211, 211, 211))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHomeLayout.createSequentialGroup()
                .addComponent(lblCustomerRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addComponent(lblCustomerRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(lblLicense))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CategoryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addComponent(lblBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(CategoryPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(BtnRegister)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtLicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicenseActionPerformed

    private void BtnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegisterActionPerformed
        CarRegisterView carRegisterView 
                = new CarRegisterView();
        
        
    }//GEN-LAST:event_BtnRegisterActionPerformed

    private void listCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listCategoriesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listCategoriesActionPerformed

    private void listCategories2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listCategories2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listCategories2ActionPerformed

    private void listCategories1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listCategories1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listCategories1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegister;
    private javax.swing.JPanel CategoryPanel;
    private javax.swing.JPanel CategoryPanel1;
    private javax.swing.JPanel CategoryPanel2;
    private javax.swing.JLabel lblBirthDate;
    private javax.swing.JLabel lblBrands;
    private javax.swing.JLabel lblCategories;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblCustomerRegister;
    private javax.swing.JLabel lblLicense;
    private javax.swing.JLabel lblName;
    private javax.swing.JComboBox<String> listCategories;
    private javax.swing.JComboBox<String> listCategories1;
    private javax.swing.JComboBox<String> listCategories2;
    private javax.swing.JPanel panelHome;
    private javax.swing.JTextField txtBirthDate;
    private javax.swing.JTextField txtLicense;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
